### ISSUE TITLE
I having troubles to send an image

### ISSUE THREAD

**Issue by elyphas** [cornerman/mycelium#11]
```scala
      val payload = Pickle.intoBytes[WebSocketEvent](msgFile)//.arrayBuffer()
      type Event = String
      type Failure = String //Int
      val client = WebsocketClient.withPayload[ByteBuffer, ByteBuffer, Event, Failure](
                        new JsWebsocketConnection, WebsocketClientConfig(), new IncidentHandler[Event])
      client.run(s"ws://$ipWS:$portWS/ws/socketMycelium")
      val respondWS = client.send ( "saveImage" :: Nil, payload, SendType.WhenConnected, 30 seconds )
```

I can't deserialize on the server side
```scala
val f = deserialize[IncomingFile](args)
```
by the way, awesome lib

**Comment by elyphas** [comment]
the idea is to send an ArrayBuffer but I don't know how to setup the websocket

**Comment by cornerman** [comment]
@elyphas Thank you for opening this issue, sadly the documentation is just not existing. In general, an example of how to use this library can be found in the tests, see https://github.com/cornerman/mycelium/blob/master/mycelium/jvm/src/test/scala/MyceliumRealSpec.scala

> val f = deserialize[IncomingFile](args)

Where in the server are you running this code and what are the `args`? Can you maybe show me the code, where you use mycelium, so I have a better idea of what is happening there?

**Comment by cornerman** [comment]
If you want a more integrated library, you might be interested in https://github.com/cornerman/covenant, where you can define a scala trait, which would either be routed through a rest api or a websocket api. Let me know, if this is interesting for you, then I will try to update the readme there for this use case.

**Comment by elyphas** [comment]
yea, I had read, all the tests, I almost understand all the things :), I made advances, I almost migrate my project just lacking send the files:
this is my `FullRequestHandler`:
https://gist.github.com/elyphas/2f3d13a52f4463fac5df64438500f2a3#file-fullrequesthandler-scala-L83

to be precise in the line 83 begin the `case "saveImage" :: Nil =>`

in the client I have this:

https://gist.github.com/elyphas/7e61e28c424ee4fe605425ab7650c7c7

**Comment by elyphas** [comment]
thank you, I will take a look at covenant,

to start could you tell me?, please, what would be the advantages over mycelium

**Comment by elyphas** [comment]
because at this moment mycelium fill all my expectations, It has all I wanted when I started to use websockets, :)

**Comment by elyphas** [comment]
also I tried this:
```scala
val client = WebsocketClient.withPayload[ByteBuffer, ArrayBuffer, Event, Failure](
                        new JsWebsocketConnection, WebsocketClientConfig(), new IncidentHandler[Event])
```
but I get this:
```scala
FrmPedido.scala:189:88: could not find implicit value for parameter serializer: chameleon.Serializer[mycelium.core.message.ClientMessage[scala.scalajs.js.typedarray.ArrayBuffer],java.nio.ByteBuffer]
[error]       val client = WebsocketClient.withPayload[ByteBuffer, ArrayBuffer, Event, Failure](
```

**Comment by elyphas** [comment]
by the way the `case class` has this structure:

```scala
final case class IncomingFile(idPedido: IdPedido, file: Array[Byte], typeFile: String, eof: Boolean) extends WebSocketEvent
```

**Comment by cornerman** [comment]
@elyphas Nice, the code looks good! But I think, you might need to serialize the `msgFile` as an `IncomingFile` because that is how you deserialize in the backend. Can you try replacing the serialization in the client with: `val payload = Pickle.intoBytes[IncomingFile](msgFile)`? You could alternatively deserialize as `WebsocketEvent` in the backend. This is because boopickle serializes differently if it is just a single case class like `IncomingFile` or a ADT hierarchy like `WebsocketEvent`.

See this example:

```scala
scala> sealed trait Foo; case class A(i:Int) extends Foo; case class B(s: String) extends Foo
defined trait Foo
defined class A
defined class B

scala> Pickle.intoBytes(A(1))
res0: java.nio.ByteBuffer = java.nio.HeapByteBuffer[pos=0 lim=2 cap=512]

scala> Unpickle[A].fromBytes(res0)
res1: A = A(1)

scala> Unpickle[Foo].fromBytes(res0)
java.nio.BufferUnderflowException
  at java.nio.Buffer.nextGetIndex(Buffer.java:500)
  at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135)
  at boopickle.DecoderSize.readInt(CodecSize.scala:62)
  at boopickle.CompositePickler.unpickle(CompositePicklers.scala:34)
  at boopickle.UnpickleImpl$UnpickledCurry.fromBytes(Default.scala:99)
  ... 36 elided
```

**Comment by cornerman** [comment]
The motivation behind covenant was to have an opinionated layer over RPC with events via http requests and websockets.

Requests and responses come natural for normal rest APIs over http, but you need a protocol to do that in websockets, which is what mycelium offers.

For the RPC part, we have built sloth (https://github.com/cornerman/sloth), which was inspired by autowire. It allows you to define a scala trait as your API and then define how you want transport the requests (method calls) from the client to the backend.

Now covenant takes akka-http for http requests, mycelium for websocket requests and sloth for defining APIs and gives you a library to once define that you want to transport your requests over http or websocket and then just call methods in a scala trait to make the actual requests.

Your example could look like this:

```scala
trait Api[F[_]] {
  def getTrue: F[Boolean]
  def saveImage(file: IncomingFile): F[Boolean]
}
```

Then you need to define you backend which lets you use events and state changes like in mycelium:
```scala
  type Event = String
  type State = String
  case class ApiError(msg: String)

  object Dsl extends ApiDsl[Event, ApiError, State] {
    override def applyEventsToState(state: State, events: Seq[Event]): State = state + " " + events.mkString(",")
    override def unhandledException(t: Throwable): ApiError = ApiError(t.getMessage)
  }

  object ApiImpl extends Api[Dsl.ApiFunction] {
    import Dsl._
    
    def getTrue: ApiFunction[Boolean] = Action(true)
    def saveImage: ApiFunction[Boolean] = Action { state =>
       ???
    }
    // or with events
    // def saveImage: ApiFunction[Boolean] = Effect { state =>
    //   val uploadFile = ???
    //   Returns(uploadFile, Seq("event-save-file"))
    // }
    // or with api errors 
    // def saveImage: ApiFunction[Boolean] = Action { state =>
    //   Returns.error(ApiError("nope"))
    // }
  }
```

Then you need to plug it into your akka route in the backend and define some specifics about the websocket configuration:
```
   val port = 9991

   val api = new WsApiConfigurationWithDefaults[Event, ApiError, State] {
     override def dsl = Dsl
     override def initialState: State = ""
     override def isStateValid(state: State): Boolean = true
     override def serverFailure(error: ServerFailure): ApiError = ApiError(error.toString)
   }

   object Backend {
     val router = Router[ByteBuffer, Dsl.ApiFunction]
       .route[Api[Dsl.ApiFunction]](DslApiImpl)

     def run() = {
       val config = WebsocketServerConfig(bufferSize = 5, overflowStrategy = OverflowStrategy.fail)
       val route = AkkaWsRoute.fromApiRouter(router, config, api)
       Http().bindAndHandle(route, interface = "0.0.0.0", port = port)
     }
   }

    Backend.run()
```

In your frontend, you can then just the `Api` trait we have defined in the beginning and you get access to all events send to your client:
```scala
    object Frontend {
      val config = WebsocketClientConfig()
      val client = WsClient[ByteBuffer, Unit, ApiError](s"ws://localhost:$port/ws", config)
      val api = client.sendWithDefault.wire[Api[Future]]
      // client.observable.connected/closed/events offers different events coming from the websocket.
    }
```

Finally, your frontend can call the backend and upload a file by doing this:
```scala
  Frontend.api.saveImage(IncomingFile(...)).foreach { success => println(s"Uploaded file: $success") }
```

I am sorry, there is not much documentation on this part, but there is one test in covenant doing exactly this: https://github.com/cornerman/covenant/blob/master/ws/jvm/src/test/scala/WsSpec.scala

Hope it helps!

**Comment by elyphas** [comment]
thank you very much, such great explanation

**Comment by elyphas** [comment]
problem solved.
client side :
```scala
val payload = Pickle.intoBytes[IncomingFile](msgFile) //.arrayBuffer()
      type PayLoad = ByteBuffer
      type Event = String
      type Failure = String
      val client = WebsocketClient.withPayload[ByteBuffer, ByteBuffer, Event, Failure](
                        new JsWebsocketConnection, WebsocketClientConfig(), new IncidentHandler[Event])
      client.run(s"ws://$ipWS:$portWS/ws/socketMyceliumImg")
      val respondWS = client.send("saveImage" :: Nil, payload, SendType.WhenConnected, 30 seconds)
```
server side: 
```scala
case "saveImage" :: Nil =>
    val f: IncomingFile = Unpickle[IncomingFile].fromBytes(args)
```

**Comment by cornerman** [comment]
Great. I am going to close this issue because it is then resolved.

Be aware that you should normally just open one `WebsocketClient` once in your app and then reference it when you make requests. Your current code looks like it is creating a new websocketclient for each image upload.
