### ISSUE TITLE
onError in server/client handler

### ISSUE THREAD

**Issue by cornerman** [cornerman/mycelium#4]
At some points we are currently just logging, we should have a callback in the handler to attach your own logger or do some other action. Or is logging with scribe good enough?

**Comment by fdietze** [comment]
A type class for logging? 😁

**Comment by cornerman** [comment]
Now I think logging is fine for the places where we have no other way to tell the consuming application. This is mostly just informing about unreadable/deserializable messages. Logging can be configured, also with listeners for slf4j (https://github.com/outr/scribe).
