### ISSUE TITLE
boopickle Payload

### ISSUE THREAD

**Issue by elyphas** [cornerman/mycelium#66]
in my connection I am doing this.
```scala   
type Payload = ByteBuffer    
type Event = String    
type Failure = String    
    
val ipServer = org.scalajs.dom.window.location.host    
val ipWSAnalytics = ipServer.substring( 0, ipServer.indexOf(":") )    
    
val portCtalogs = "7777"    
    
val ws = WebsocketClient.withPayload[ByteBuffer, ByteBuffer, Event, Failure](    
                new JsWebsocketConnection, WebsocketClientConfig(), new IncidentHandler[Event])
```
and when I send data I do this.
```scala
val payload   = Pickle.intoBytes[String](idComparative)    
val respondWS = WSMyCeliumAnalytics.ws.send("getMinimosRetensionISR" :: Nil, payload, SendType.WhenConnected, 100 seconds)
```
but seems I doing double pickling and thats wrong, am I right?

the `Payload` must be `String` and mycelium is going to do the `Pickle.intoBytes` inside it?

**Comment by cornerman** [comment]
You can set the Payload to String and pickle the whole message (including the Payload) into a ByteBuffer.

This is correct:
`WebsocketClient.withPayload[ByteBuffer, String, Event Failure](...)`

If you have the same type for both, the Payload and the PickleType, then you will indeed double-serialize. Though that might be ok in some use-cases.
